name: workflow overview

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  a_simple_job:
    name: my simple job
    runs-on: ubuntu-latest
    steps:
      - name: name of my step
        id: stepId
        run: echo "this is the first step from the first job"
      - name: step with another shell
        id: shellStep
        shell: python
        run: print("this is using the python shell")
  my_self-hosted-job:
    name: my self hosted job
    runs-on: self-hosted
    steps:
      - name: steps in self hosted runner
        id: selfHostedId
        shell: sh
        run: |
          echo this is a multiline comment
          echo and this job has been excecuted from my self-hosted runner
      
